### ISSUE TITLE
Docker pull denied

### ISSUE THREAD

**Issue by smilejinho** [allenai/vessel-detection-viirs#10]
Hi~ 
I am trying to use this great codes of "vessel-detection-viirs".

First, I tried with docker pull, but it does not work.
---
# docker pull ghcr.io/vulcanskylight/vessel-detection-viirs:latest
Error response from daemon: Head "https://ghcr.io/v2/vulcanskylight/vessel-detection-viirs/manifests/latest": denied
---

And, I tryin to build from source.
But it makes error.
---
ERROR tests/test_main.py::TestApiLocalFiles::test_acquisition_time - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/test_main.py::TestApiLocalFiles::test_filename - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/test_main.py::TestApiLocalFiles::test_frame_extents - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/test_main.py::TestApiLocalFiles::test_moonlight_illumination - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/test_main.py::TestApiLocalFiles::test_predictions_count - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/test_main.py::TestApiLocalFiles::test_response_code - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/test_main.py::TestApiLocalFiles::test_response_size_under_one_megabyte - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/test_main.py::TestApiLocalFiles::test_status - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
---

Am I doing something wrong ?

Thanks.

**Comment by smilejinho** [comment]
The errors of build from source is the result of "pytest tests -vv".

**Comment by pbeukema** [comment]
Thank you for the comment. 

I am not sure exactly what that error indicates. Here are two possible solutions. 

1. The example files (in tests/) are stored on GitHub via git-lfs. It is required to install git-lfs to download these files. Are these files available (and are they accessible from within the container via the passed mount arg?
2. I have uploaded additional files and stored them in the example (and they are stored via conventional means and not dependent on git-lfs). I.e. if you clone the repo, those files should be present within the example directory. 

With option 2, you should be able to run the docker command (with the updated mount location), without git-lfs. I uploaded updated the example request (which points to these new non git-lfs stored files), and uploaded the corresponding new sample_response.json.

If neither of those work, could you please paste the commands that you are using (including the docker run command), and I will see if i can reproduce the error.

**Comment by smilejinho** [comment]
Thanks for your quick react.
It works now.

**Comment by smilejinho** [comment]
Close.
