### ISSUE TITLE
Can I use this with geotiff file ?

### ISSUE THREAD

**Issue by smilejinho** [allenai/vessel-detection-viirs#14]
Hi.

I am new to viirs image processing domain.
And I need to make an application to detect vessels in viirs "geotiff" file.

I don't know the exact differences of nc(netcdf) and geotiff file.
I tested this "vessel-detection-viirs" great codes,
and I see this vdv(vessel-detection-viirs) requires "DNB" and "GEO" files.

But my customer just have "GEOTIFF" file.
The file name looks like "2023.1119.1746.npp.DNB.geotiff".

What should I do with this file(.geotiff) ?
Can I use vdv(vessel-detection-viirs) with just this geotiff file ?

Thanks.

**Comment by pbeukema** [comment]
We don't support non netcdf files -- as the model is specific to these satellites/data sources. Can you provide a link to the url/data that you are referring to in 2023.1119.1746.npp.DNB.geotiff and I will take a look.

**Comment by smilejinho** [comment]
You can download the file from below url.
https://drive.google.com/file/d/15ExDn1LDe3QWSAOKqAPJ4hwTy2mD9AkZ/view?usp=sharing
Thanks.

**Comment by pbeukema** [comment]
Thanks -- can you provide the original source url of this file? NASA produces geo arrays (the geo data) alongside the DNB data for both satellites, so geotiffs are not needed for suomi-npp or NOAA-20 (enabling numpy based indexing, and eliminates the need for rasterio/gdal and other geo libraries). We have evaluated both approaches, and the way it is done in this code base is faster, has a smaller memory footprint, and is computationally much more efficient.

**Comment by smilejinho** [comment]
I asked to my customer but he saids he can only provide  geotiff.
I think I should find the other method.
Thanks for your supports.
